name: Build Adélie Game Engine (Linux)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Install required dependencies...
        run: sudo apt update && sudo apt install -y cmake clang libgl-dev libglx-dev libboost-all-dev libyaml-cpp-dev libmsgsl-dev libvulkan-dev vulkan-utility-libraries-dev libxcb1-dev libxcb-icccm4-dev libwayland-dev pkg-config wayland-protocols
      - name: Configure the project using CMake...
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++
      - name: Building the engine code...
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target adelie_engine
