name: Build Adélie Game Engine (Windows)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Install required dependencies...
        uses: johnwason/vcpkg-action@v7
        id: vcpkg
        with:
          pkgs: boost-stacktrace boost-thread yaml-cpp ms-gsl freetype vulkan vulkan-tools vulkan-validationlayers vulkan-utility-libraries
          triplet: x64-windows-release
          token: ${{ github.token }}
      - name: Configure the project using CMake...
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-release -DVCPKG_MANIFEST_MODE=OFF
      - name: Building the engine code...
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target adelie_engine
